### ISSUE TITLE
Feedback: 'get' function not available on MacOS 10.12.6

### ISSUE THREAD

**Issue by jasnow** [sorbet/sorbet#1281]
Ran **bazel build //main:sorbet --config=dbg --verbose_failures**
on a 10.12.6 and get these 4 errors:
```
ERROR: /Users/USER/Projects/sorbet/main/lsp/BUILD:1:1: C++ compilation of rule '//main/lsp:lsp' failed (Exit 1): cc_wrapper.sh failed: error executing command
main/lsp/requests/sorbet_workspace_edit.cc:155:48: error: call to unavailable function 'get': introduced in macOS 10.14
main/lsp/requests/sorbet_workspace_edit.cc:159:48: error: call to unavailable function 'get': introduced in macOS 10.14
main/lsp/requests/sorbet_workspace_edit.cc:163:48: error: call to unavailable function 'get': introduced in macOS 10.14
main/lsp/requests/sorbet_workspace_edit.cc:167:48: error: call to unavailable function 'get': introduced in macOS 10.14
4 errors generated.
```

**Comment by DarkDimius** [comment]
@jasnow adding `--config=static-libs` should fix it.
We don't set it by default as `--config=dbg` is optimized for our laptop setup

**Comment by jasnow** [comment]
Tried "--config=static-libs" (no change) so tried --sandbox-debug (3 more errors)  so did the "--config=static-libs again and got this: https://gist.github.com/jasnow/de296fe5c17a4940a8f4a43ba7a49877

**Comment by DarkDimius** [comment]
could you try adding `--copt=-D_LIBCPP_DISABLE_AVAILABILITY` to command line?

**Comment by DarkDimius** [comment]
https://github.com/llvm-mirror/libcxx/blob/2ae08ad852f35bfff251e4332a122a07013c8bed/include/__config#L1313

**Comment by jasnow** [comment]
Still getting the original 5 (above) errors for
```
bazel build //main:sorbet --verbose_failures --config=static-libs --copt=-D_LIBCPP_DISABLE_AVAILABILITY
```
When I run "gcc --version" I get:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jasnow** [comment]
Will reopen if things change.

**Comment by fzakaria** [comment]
For what it's worth -- I'm hitting this as I try to create a homebrew file for sorbet.
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52761/version=highsierra/testReport/junit/brew-test-bot/high_sierra/install___build_bottle_sorbet/

It's failing to build on high_sierra & catalina.
Confusing since it looks like `llvm_toolchain` is setup so it shouldn't be using the system's llvm compiler.

**Comment by DarkDimius** [comment]
@fzakaria did you try https://github.com/sorbet/sorbet/issues/1281#issuecomment-511543604 ?

**Comment by DarkDimius** [comment]
also, if you're building this for it to be downloadable by people, you may want to remove ` --config=debugsymbols`, as it makes huge binaries(~300M)

**Comment by fzakaria** [comment]
Will try both thanks @DarkDimius

**Comment by fzakaria** [comment]
@DarkDimius i tried including `--copt=-D_LIBCPP_DISABLE_AVAILABILITY` however it's failing to build on non-Mojave. I would appreciate any feedback -- I'm fairly close to getting the brew formula.

You can see the failure: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52794/version=highsierra/console

What's also odd is that Catalina is building but failing to exec (https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52794/version=catalina/testReport/junit/brew-test-bot/catalina/test_sorbet/)

I'll have to inspect the binary file produced https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52794/version=catalina/artifact/sorbet--0.4.5085.catalina.bottle.tar.gz

**Comment by DarkDimius** [comment]
> You can see the failure: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/52794/version=highsierra/console

try adding `--host_copt=-D_LIBCPP_DISABLE_AVAILABILITY`. Though at that point you're in unsupported territory even harder.

> What's also odd is that Catalina is building but failing to exec

This is strange. IDK what's happening there.

Is it an option for you to just download binaries that we publish in https://github.com/sorbet/sorbet/releases ?

**Comment by fzakaria** [comment]
I might also do what you suggest and offer a formula for the prebuilt binaries. 

Homebrew refers to them as "casks" and they aren't as great as building from source but at this point /shrug 

Thanks for the feedback.

**Comment by fzakaria** [comment]
I've uploaded a PR for homebrew cask --> https://github.com/Homebrew/homebrew-cask/pull/73495

This will just install the prebuilt binary.
