### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#2388]
#### Input

I'm testing out Ruby 2.7 and [this line](https://github.com/sorbet/sorbet/blob/1b7009d007f8ed838eb18a825cf15516871de77d/gems/sorbet-runtime/lib/types/private/methods/call_validation.rb#L126) is causing deprecation warnings for me wherever a method with a sig is called and validated (the method may need to have keyword arguments to trigger the deprecation warning?).

You can see an explanation of the kwargs deprecation in [this blog post](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/).

A simplified example:

```ruby
# typed: true
class Helper
  extend T::Sig

  # Takes an array and creates a humanized string out of it.
  sig { params(array: T::Array[String], limit: Integer).returns(T.nilable(String)) }
  def self.summarize(array, limit: 3)
    raise ArgumentError, 'Limit must be a positive integer' unless limit.positive?

    return "#{array.first} and #{(array.length - limit)} more" if limit == 1 && array.length > 1
    return "#{T.must(array[0...limit]).join(', ')}, and #{(array.length - limit)} more" if array.length > limit
    return array.join(', ') if array.length <= limit
  end
end

# This next line will cause a deprecation warning to be printed on Ruby 2.7 because it goes through Sorbet's call validation.
Helper.summarize(['PlayStation 2', 'Xbox 360'], limit: 1)
```

#### Observed output

```
/Users/connorshea/.rbenv/versions/2.7.0-preview3/lib/ruby/gems/2.7.0/gems/sorbet-runtime-0.4.5133/lib/types/private/methods/call_validation.rb:126: warning: The last argument is used as the keyword parameter
/Users/connorshea/Programming/vglist/app/helpers/application_helper.rb:85: warning: for `summarize' defined here
```

#### Expected behavior

I'd expect it not to produce deprecation warnings.

Tested on Sorbet 0.4.5133 and Ruby 2.7.0-preview3, but I don't see any changes that would effect this issue since 0.4.5133.

**Comment by jaredbeck** [comment]
There's a discussion going on today about kwargs in ruby 3.0.

https://discuss.rubyonrails.org/t/new-2-7-3-0-keyword-argument-pain-point/74980

Matz is asking about pain points and a lot of library maintainers have chimed in. I think you'll find it interesting.

**Comment by connorshea** [comment]
I think this is fixed now? There's still a deprecation warning on 2.7 when generating hidden definitions, but it isn't this one (and I have a PR open to fix that remaining existent one).

**Comment by aprocter-stripe** [comment]
I'm unable to reproduce this with Ruby 2.7.4 and Sorbet 0.5.6508, so per that and @connorshea's last comment I think this must have been fixed. Closing, but if anyone runs into this on recent versions of Sorbet please feel to reopen.

**Comment by jez** [comment]
Ruby 2.7.2 silenced all deprecation warnings by default. The warnings are still there, but not printed.

The issue was likely reported against Ruby 2.7.1, and likely indicates that there will be an error on Ruby 3.0.

**Comment by aprocter-stripe** [comment]
> Ruby 2.7.2 silenced all deprecation warnings by default. The warnings are still there, but not printed.
> 
> The issue was likely reported against Ruby 2.7.1, and likely indicates that there will be an error on Ruby 3.0.

Good point. I tried with both `-W1` and `-W2` so I think even 2.7.4 would have caught it, but just to make sure I ran it again with 2.7.1. Still doesn't reproduce.
